import random

subjects = [
    "Albert Einstein",
    "Taylor Swift",
    "A Street Magician from Paris",
    "A Golden Retriever",
    "A Space Scientist from NASA",
    "A Chef in Tokyo",
    "A Taxi Driver in New York",
    "A Panda Eating Bamboo",
    "The Eiffel Tower",
    "A School Teacher in London",
    "A Polar Bear in Antarctica",
    "A Group of Street Dancers",
    "A Farmer in Punjab",
    "A Surfer on a Hawaiian Beach",
    "A Pilot Flying an Airplane",
    "A Nurse in a City Hospital",
    "A Carpenter from Mexico",
    "An Old Lighthouse Keeper",
    "A Chess Grandmaster",
    "A Mountain Climber on Everest",
    "A Dolphin in the Ocean",
    "An Astronaut on the Moon",
    "A Robot Painter",
    "A Buddhist Monk",
    "A Librarian in a Small Town",
    "A Flamenco Dancer",
    "A Baker Making Bread",
    "A Cloud in the Sky",
    "A Photographer in the Jungle",
    "A Detective in London",
    "A Firefighter Saving Lives",
    "A Soldier at the Border",
    "A Marathon Runner",
    "A Snow Leopard in the Himalayas",
    "A Street Vendor in Bangkok",
    "A Child with a Kite",
    "A Scientist in a Lab",
    "A News Reporter from CNN",
    "A Gamer Streaming Online",
    "A SpaceX Engineer",
    "A Violinist in an Orchestra",
    "A Beekeeper in Brazil",
    "A Potter Making Clay Pots",
    "A Village Headman",
    "A Fashion Designer in Milan",
    "A Barber in a Busy Market",
    "A Taxi in Mumbai",
    "A Fisherman in Kerala",
    "A Flight Attendant",
    "A Lawyer in Court",
    "A Priest in a Church",
    "A Photographer at a Wedding",
    "A Forest Ranger",
    "A Student Studying at Night",
    "A Street Dog in Delhi",
    "A Farmer Plowing the Field",
    "A Cyclist in the Race",
    "A Skydiver over Dubai",
    "A News Anchor on TV",
    "A Tattoo Artist",
    "A School Principal",
    "A Bus Conductor in Chennai",
    "A Shopkeeper in a Small Town",
    "A Judge in the Supreme Court",
    "A Filmmaker from Hollywood",
    "A Parrot in a Cage",
    "A Doctor Treating Patients",
    "A Soccer Player",
    "A Cloud Computing Engineer",
    "A Singer in a Rock Band",
    "A Football Coach",
    "A Painter in Paris",
    "A Farmer Harvesting Rice",
    "A Railway Ticket Collector",
    "A Postman Delivering Mail",
    "A Social Worker",
    "A Taxi Passenger",
    "A Zoo Keeper",
    "A Nurse Giving Injection",
    "A Chef in a Luxury Hotel",
    "A Shop Assistant",
    "A Guitarist on Stage",
    "A Police Officer in Uniform",
    "A Tourist in Rome",
    "A Software Developer",
    "A Construction Worker",
    "A Tailor Sewing Clothes",
    "A Plumber Fixing Pipes",
    "A Yoga Instructor",
    "A Delivery Boy on a Scooter",
    "A Marathon Volunteer",
    "A Wildlife Photographer",
    "A Teacher Explaining a Lesson",
    "A Typist in an Office",
    "A Clerk in a Government Office",
    "A Painter with a Brush",
    "A Sculptor Making a Statue",
    "A Politician Giving Speech",
    "A Student in College",
    "A Researcher in AI",
    "A Taxi Stand Manager",
    "A Nurse in ICU",
    "A Doctor Doing Surgery",
    "A Baker Baking Cookies",
    "A Programmer Debugging Code",
    "A Data Scientist",
    "A Machine Learning Engineer",
    "A Football Referee",
    "A Delivery Drone",
    "A Street Musician",
    "A Graphic Designer",
    "A Photographer in the Rain",
    "A Librarian Organizing Books",
    "A Kid Playing with Lego",
    "A Dog Trainer",
    "A Snake Charmer",
    "A Waiter Serving Food",
    "A Mechanic Repairing a Car",
    "A Pilot Landing the Plane",
    "A Barber Cutting Hair",
    "A Taxi Driver in London",
    "A Mountaineer in the Alps",
    "A Child Reading a Book",
    "A Tour Guide in Egypt",
    "A Factory Worker",
    "A Grocery Store Cashier",
    "A DJ Playing Music",
    "A Magician on Stage",
    "A Tattoo Designer",
    "A Nurse Checking Blood Pressure",
    "A Doctor Consulting a Patient",
    "A Farmer Milking a Cow",
    "A Chef Making Pizza",
    "A Taxi Driver from Delhi",
    "A Street Artist Painting Walls",
    "A Researcher Studying Viruses",
    "A Photographer on a Cliff",
    "A Space Rover",
    "A Soldier Saluting the Flag",
    "A Child Playing Football",
    "A Swimmer in the Pool",
    "A Bird Flying High",
    "A Cat Sleeping on a Couch",
    "A Dog Running in the Park",
    "A Horse Galloping",
    "A Fish Swimming in the Pond",
    "A Monkey Stealing Fruits",
    "A Cow Grazing",
    "A Farmer in the Field",
    "A Policeman on Patrol",
    "A Clerk Typing on Computer",
    "A Doctor Writing Prescription",
    "A Nurse Giving Medicine",
    "A Patient Resting on Bed",
    "A Scientist Working with Microscope",
    "A Student Writing Exam",
    "A Professor Delivering Lecture",
    "A Lawyer Presenting Case",
    "A Judge Announcing Verdict",
    "A Reporter Interviewing Someone",
    "A Cameraman Filming Scene",
    "A Director Shouting Action",
    "A Film Editor",
    "A Movie Actor",
    "A Radio Host",
    "A Pilot Flying Helicopter",
    "A Cabin Crew Member",
    "A Tourist with a Camera",
    "A Hiker with Backpack",
    "A Cyclist on the Road",
    "A Jogger in the Morning",
    "A Street Vendor Selling Fruits",
    "A Bus Driver in Traffic",
    "A Rickshaw Puller",
    "A Student in Library",
    "A Kid Flying a Kite",
    "A Group of Friends at Cafe",
    "A Photographer Taking Sunset Shot",
    "A Cat Chasing Mouse",
    "A Dog Barking at Stranger",
    "A Bird Nesting in Tree",
    "A Cloud Passing by",
    "A Star Twinkling",
    "A Moon Rising",
    "A Sun Setting",
    "A Tree in Forest",
    "A Flower Blooming",
    "A Butterfly on Leaf",
    "A Bee Collecting Nectar",
    "A Farmer Watering Crops",
    "A Soldier Standing Guard",
    "A Teacher Writing on Blackboard",
    "A Child Drawing Picture",
    "A Musician Playing Piano",
    "A Violin Player",
    "A Saxophone Artist",
    "A Drummer Performing",
    "A Singer Rehearsing",
    "A Dancer Practicing",
    "A Photographer Clicking Portraits",
    "A Developer Coding Website",
    "A Student Learning Python",
    "A Teacher Explaining Algorithm",
    "A Professor Teaching Physics",
    "A Doctor Researching Cure",
    "A Surgeon Performing Operation",
    "A Nurse Taking Notes",
    "A Patient Recovering",
    "A Pharmacist Dispensing Medicine",
    "A Technician Fixing Computer",
    "A Mechanic Repairing Bike",
    "A Driver Honking Horn",
    "A Shopkeeper Arranging Shelves",
    "A Security Guard Watching CCTV",
    "A Chef Preparing Salad",
    "A Waiter Cleaning Table",
    "A Manager Checking Bills",
    "A Customer Paying Bill",
    "A Tourist Taking Selfie",
    "A Family Traveling by Train",
    "A Couple Walking on Beach",
    "A Boy Feeding Pigeons",
    "A Girl Buying Ice Cream",
    "A Group of Tourists in Bus",
    "A Street Dog Sleeping",
    "A Bird Singing in Morning",
    "A Monkey Sitting on Tree",
    "A Peacock Dancing in Rain",
    "A Frog Jumping in Pond",
    "A Snake Crawling on Ground",
    "A Tiger Roaring in Jungle",
    "A Lion Walking Proudly",
    "A Zebra Running in Grassland",
    "An Elephant Bathing in River",
    "A Deer Drinking Water",
    "A Crocodile Resting on Shore",
    "A Penguin Sliding on Ice",
    "A Seal Playing with Ball",
    "A Whale Jumping in Ocean",
    "A Dolphin Splashing Water",
    "A Turtle Swimming Slowly"
]


actions = [
    "launches",
    "cancels",
    "dances with",
    "eats",
    "declares war on",
    "orders",
    "celebrates",
    "invents",
    "discovers",
    "designs",
    "builds",
    "destroys",
    "fixes",
    "paints",
    "writes about",
    "reads",
    "plays with",
    "drives",
    "flies to",
    "visits",
    "meets",
    "helps",
    "challenges",
    "fights with",
    "hugs",
    "kisses",
    "supports",
    "arrests",
    "joins",
    "starts",
    "finishes",
    "creates",
    "tests",
    "buys",
    "sells",
    "wins against",
    "loses to",
    "teaches",
    "learns from",
    "calls",
    "texts",
    "emails",
    "laughs at",
    "cries over",
    "shouts at",
    "sings to",
    "dances for",
    "paints for",
    "draws with",
    "programs",
    "codes with",
    "develops",
    "installs",
    "repairs",
    "hides from",
    "runs toward",
    "walks with",
    "jumps over",
    "swims across",
    "climbs",
    "travels to",
    "returns from",
    "proposes to",
    "marries",
    "divorces",
    "congratulates",
    "celebrates with",
    "apologizes to",
    "forgives",
    "questions",
    "answers",
    "invites",
    "welcomes",
    "greets",
    "warns",
    "advises",
    "announces",
    "confirms",
    "denies",
    "accepts",
    "rejects",
    "signs",
    "draws",
    "shoots",
    "records",
    "films",
    "broadcasts",
    "streams",
    "uploads",
    "downloads",
    "posts about",
    "comments on",
    "likes",
    "shares",
    "retweets",
    "blocks",
    "unblocks",
    "follows",
    "unfollows",
    "tags",
    "mentions",
    "reviews",
    "rates",
    "criticizes",
    "praises",
    "supports",
    "funds",
    "donates to",
    "volunteers for",
    "organizes",
    "hosts",
    "attends",
    "misses",
    "plans",
    "forgets",
    "remembers",
    "imagines",
    "dreams of",
    "thinks about",
    "analyzes",
    "calculates",
    "solves",
    "explains",
    "defines",
    "discovers",
    "explores",
    "tests",
    "publishes",
    "reviews",
    "translates",
    "researches",
    "measures",
    "predicts",
    "forecasts",
    "draws conclusions about",
    "debates with",
    "argues with",
    "negotiates with",
    "signs agreement with",
    "breaks agreement with",
    "sues",
    "defends",
    "protects",
    "attacks",
    "saves",
    "rescues",
    "escapes from",
    "chases",
    "captures",
    "hunts",
    "feeds",
    "raises",
    "adopts",
    "releases",
    "finds",
    "loses",
    "buys from",
    "sells to",
    "borrows from",
    "lends to",
    "invests in",
    "earns from",
    "spends on",
    "saves for",
    "steals from",
    "donates to",
    "gives to",
    "receives from",
    "thanks",
    "insults",
    "argues with",
    "debates with",
    "agrees with",
    "disagrees with",
    "collaborates with",
    "partners with",
    "visits",
    "travels with",
    "flies over",
    "sails to",
    "drives to",
    "walks to",
    "runs to",
    "hides behind",
    "looks for",
    "searches for",
    "finds",
    "admires",
    "observes",
    "records",
    "films",
    "photographs",
    "paints",
    "sketches",
    "sculpts",
    "writes to",
    "emails",
    "calls",
    "texts",
    "shouts at",
    "waves at",
    "smiles at",
    "bows to",
    "salutes",
    "greets",
    "meets with",
    "visits",
    "travels with",
    "returns from",
    "enters",
    "leaves",
    "joins",
    "quits",
    "resigns from",
    "hires",
    "fires",
    "promotes",
    "demotes",
    "trains",
    "supervises",
    "manages",
    "directs",
    "produces",
    "edits",
    "publishes",
    "prints",
    "advertises",
    "markets",
    "sponsors",
    "endorses",
    "represents",
    "votes for",
    "campaigns for",
    "protests against",
    "supports",
    "defends",
    "criticizes",
    "boycotts",
    "funds",
    "investigates",
    "questions",
    "confirms",
    "announces",
    "explains",
    "demonstrates",
    "shows",
    "hides",
    "reveals",
    "leaks",
    "publishes",
    "reports",
    "interviews",
    "comments on",
    "reviews",
    "debates about",
    "reacts to",
    "responds to",
    "replies to",
    "thanks",
    "forgives",
    "blames",
    "accuses",
    "confesses to",
    "admits",
    "denies",
    "warns",
    "encourages",
    "motivates",
    "inspires",
    "teaches",
    "learns from",
    "studies",
    "practices",
    "tests",
    "improves",
    "creates",
    "builds",
    "repairs",
    "decorates",
    "cleans",
    "washes",
    "organizes",
    "prepares",
    "cooks",
    "bakes",
    "serves",
    "eats",
    "drinks",
    "tastes",
    "offers",
    "refuses",
    "gives",
    "takes",
    "opens",
    "closes",
    "locks",
    "unlocks",
    "starts",
    "stops",
    "turns on",
    "turns off",
    "charges",
    "unplugs",
    "uploads",
    "downloads",
    "installs",
    "updates",
    "restarts",
    "fixes",
    "uses",
    "controls",
    "commands",
    "operates",
    "drives",
    "flies",
    "pilots",
    "navigates",
    "steers",
    "lands",
    "launches",
    "programs",
    "codes",
    "debugs",
    "compiles",
    "executes",
    "runs",
    "tests",
    "deploys",
    "monitors",
    "optimizes",
    "analyzes",
    "simulates",
    "calculates",
    "predicts"
]


places_or_things = [
    "at Red Fort",
    "in Mumbai Local Train",
    "a plate of samosa",
    "inside parliament",
    "at Ganga Ghat",
    "during IPL Match",
    "at India Gate",
    "at Eiffel Tower",
    "on the Great Wall of China",
    "in Times Square",
    "inside a Metro Station",
    "at a Wedding Hall",
    "in a Coffee Shop",
    "at Marine Drive",
    "on a Fishing Boat",
    "in a Jungle Safari",
    "at a Cricket Stadium",
    "at Taj Mahal",
    "on a Rooftop",
    "in a School Classroom",
    "at a Railway Station",
    "in a Hospital Ward",
    "on a Rainy Street",
    "inside a Movie Theater",
    "in a College Canteen",
    "at a Beach Party",
    "at the Bus Stop",
    "at a Temple",
    "in a Mosque",
    "inside a Church",
    "at Gateway of India",
    "in a Shopping Mall",
    "on a Flight",
    "in a Taxi",
    "inside a Library",
    "in a Computer Lab",
    "at a Construction Site",
    "on a Football Field",
    "at a Police Station",
    "inside a Museum",
    "at a Hill Station",
    "in a Luxury Hotel",
    "at a Marriage Ceremony",
    "inside a Metro Train",
    "in a Vegetable Market",
    "at a Music Concert",
    "inside a Restaurant",
    "at a Tea Stall",
    "in a Movie Set",
    "on a Cruise Ship",
    "at a Science Fair",
    "in a Gaming Arena",
    "at a Gym",
    "inside a Car",
    "at a Bus Terminal",
    "on a Highway",
    "in a Mountain Camp",
    "at a Railway Crossing",
    "in a Cow Shed",
    "at a Petrol Pump",
    "in a Factory",
    "inside a Classroom",
    "at a Playground",
    "on a Farm",
    "in a Desert",
    "under a Tree",
    "on the Moon",
    "in Space Station",
    "on a Bridge",
    "at a Waterfall",
    "at a Bakery Shop",
    "in a Restaurant Kitchen",
    "at an Art Gallery",
    "in a Recording Studio",
    "on a Film Set",
    "in a Coffee Café",
    "at a Flower Market",
    "in a Jewelry Store",
    "at a Shopping Street",
    "in a Small Village",
    "at a Bus Depot",
    "in a Train Compartment",
    "on a Balcony",
    "at a Zoo",
    "in a Garden",
    "at a Festival",
    "at a Political Rally",
    "during a Press Conference",
    "in a News Studio",
    "on a Radio Show",
    "at a Mountain Peak",
    "in a Ski Resort",
    "at a Beach Resort",
    "in a Forest Cabin",
    "in an Igloo",
    "at a Campfire",
    "in a Tent",
    "at an Airport Lounge",
    "on a Runway",
    "at a Bus Stop",
    "in a Rickshaw",
    "in a Metro Coach",
    "inside a Lift",
    "on a Roller Coaster",
    "in an Amusement Park",
    "at Disneyland",
    "at a Carnival",
    "in a Science Lab",
    "at a Startup Office",
    "inside a Tech Company",
    "in a Meeting Room",
    "at a Conference Hall",
    "in a Seminar",
    "at a Coding Hackathon",
    "at a Robotics Expo",
    "in a Data Center",
    "in a Library Corner",
    "at a College Hostel",
    "in a School Playground",
    "at an Election Booth",
    "at a Temple Festival",
    "in a Wedding Procession",
    "at a Night Club",
    "in a Bookstore",
    "at a Pet Shop",
    "in a Spa Center",
    "at a Hair Salon",
    "in a Boutique",
    "at a Tailor Shop",
    "at a Barber Shop",
    "in a Bank",
    "at an ATM",
    "in a Post Office",
    "inside a Police Van",
    "at a Fire Station",
    "on a Speed Boat",
    "in a Submarine",
    "on a Cargo Ship",
    "at a Fishing Port",
    "on a Hilltop",
    "at a Mountain Lake",
    "in a Snowy Village",
    "on a Cable Car",
    "at a Sunset Point",
    "in a Flower Garden",
    "at a National Park",
    "in a Safari Jeep",
    "at a Meditation Center",
    "in a Yoga Studio",
    "at a Temple Pond",
    "on a Bridge over River",
    "at a City Square",
    "at a Bus Stand",
    "at a Traffic Signal",
    "in a Parking Lot",
    "on a Crowded Street",
    "at a Street Market",
    "at a Food Truck",
    "in a Juice Shop",
    "at a Street Corner",
    "on a Bench in Park",
    "at a Movie Premiere",
    "in a Recording Booth",
    "on a Stage",
    "at a Music Festival",
    "in a Theatre Hall",
    "at a Film Festival",
    "in a Newsroom",
    "on a Live Show",
    "at a TV Studio",
    "inside an Elevator",
    "on a Train Platform",
    "in a Classroom Bench",
    "at a Canteen Counter",
    "at a Food Court",
    "in a Shopping Plaza",
    "at a Bank Queue",
    "in a Waiting Room",
    "at a Doctor’s Clinic",
    "in an Ambulance",
    "at a City Hospital",
    "in a Dental Clinic",
    "at a Medical Store",
    "on a Beach",
    "at a Sunset Point",
    "in a Boat Ride",
    "on a Jet Ski",
    "at a Lighthouse",
    "in an Aquarium",
    "at a Pet Shelter",
    "in a Cow Farm",
    "at a Poultry Farm",
    "in a Dairy",
    "on a Tractor",
    "in a Paddy Field",
    "at a Sugarcane Field",
    "in a Flower Farm",
    "at a Vineyard",
    "in a Tea Garden",
    "at a Coffee Plantation",
    "at a Rubber Factory",
    "in a Textile Mill",
    "in a Workshop",
    "at a Printing Press",
    "in a Furniture Shop",
    "at a Hardware Store",
    "in a Garage",
    "at a Repair Shop",
    "in a Gas Station",
    "on a Train Track",
    "at a Signal Cabin",
    "in a Control Room",
    "at a Power Plant",
    "in a Solar Farm",
    "at a Windmill Field",
    "in a Nuclear Facility",
    "on a Space Station",
    "at the International Airport",
    "in a Control Tower",
    "on a Rocket Launchpad",
    "at a Planetarium",
    "in an Observatory",
    "at a Science Museum",
    "in a Classroom Lab",
    "at a Startup Incubator",
    "in a University Campus",
    "on a College Stage",
    "in a Lecture Hall",
    "at a Library Desk",
    "on a Sports Ground",
    "at a Gymnasium",
    "in a Swimming Pool",
    "at a Basketball Court",
    "in a Football Stadium",
    "at a Marathon Track",
    "on a Tennis Court",
    "at a Chess Tournament",
    "in a Dance Studio",
    "at an Art Workshop",
    "in a Photo Studio",
    "at a Painting Exhibition",
    "in a Sculpture Hall",
    "at a Cultural Festival",
    "in a Music Academy",
    "at a Temple Fair",
    "on a River Bank",
    "at a Ferry Terminal",
    "in a Port City",
    "at a Fish Market",
    "in a Coconut Grove",
    "at a Mango Orchard",
    "in a Rice Field",
    "at a Village Fair",
    "in a Desert Camp",
    "at a Camel Fair",
    "on a Sand Dune",
    "in a Caravan",
    "at a Border Post",
    "in a Military Base",
    "at a Parade Ground",
    "on a Battlefield",
    "at a War Memorial",
    "in a Peace Summit",
    "at a Sports Award Show",
    "in a Film Award Night",
    "at a Tech Conference",
    "on a Zoom Call",
    "in a Podcast Studio",
    "at a Hackathon",
    "in a Virtual Classroom",
    "on a Video Call",
    "at a Digital Art Fair",
    "in a 3D Printing Lab",
    "at a Drone Race",
    "on a Space Mission"
]


while True:
    subject = random.choice(subjects)
    action = random.choice(actions)
    place_or_thing = random.choice(places_or_things)

    headline = f" BREAKING NEWS: {subject} {action} {place_or_thing} "
    print("\n" + headline)

    user_input = input("\nDo you want another headline? (yes/no)").strip().lower()
    if user_input == "no":
        break

print("\nThanks for using the Fake News Headline Generator. Have a Fun Day")